apiVersion: v1
kind: Service
metadata:
  name: microservice-in-go
  labels:
    app: microservice-in-go
    tier: service
spec:
  # use NodePort here to be able to access a port on each node
  type: NodePort
  ports:
  - port: 9090
  selector:
    app: microservice-in-go