version: '2'

services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - my-net

  go-microservice-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: go-microservice-server:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - my-net

  go-microservice-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: go-microservice-client:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
      - go-microservice-server
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
