version: '2'

services: 
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - my-net

  protobuf-hystrix-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: protobuf-hystrix-server:1.0.0
    environment: 
    - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - my-net

  protobuf-hystrix-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: protobuf-hystrix-client:1.0.0
    environment: 
    - CONSUL_HTTP_ADDR=consul:8500 
    depends_on:
      - consul
      - protobuf-hystrix-server
    networks:
      - my-net

  hystrix-dashboard:
    image: mlabouardy/hystrix-dashboard:latest
    ports:
      - "9002:9002"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
  