version: '2'

services:
  protobuf-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: protobuf-server:1.0.0
    networks:
      - my-net

  protobuf-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: protobuf-client:1.0.0
    depends_on:
      - protobuf-server
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
