version: '2'

services:
  zookeeper:
    image: dockerkafka/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "5000:5000"
    networks:
      - my-net

  kafka:
    image: dockerkafka/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    networks:
      - my-net

  kafka-producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    image: kafka-producer:1.0.0
    environment:
      - BROKER_ADDR=kafka:9092
    depends_on:
      - zookeeper
      - kafka
    links:
      - kafka
    networks:
      - my-net

  kafka-consumer:
    build:
      context: .
      dockerfile: subscriber/Dockerfile
    image: kafka-consumer:1.0.0
    environment:
      - BROKER_ADDR=kafka:9092
    depends_on:
      - zookeeper
      - kafka
    links:
      - kafka
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
